# Makefile for the first C++ bag
#

run_exam : test
	./test

run_test : bagtest
	./bagtest

test	: bag2.o test.o
	g++ -o test -std=c++14 test.o bag2.o

test.o  : test.cxx bag2.h
	g++ -c -std=c++14 test.cxx

bagtest : bag2.o bagtest.o
	g++ -o bagtest -std=c++14 bagtest.o bag2.o

bagtest.o : bagtest.cxx bag2.h
	g++ -c -std=c++14 bagtest.cxx

bag2.o : bag2.cxx bag2.h
	g++ -c -std=c++14 bag2.cxx

check	: test .valgrindrc
	valgrind ./test

doxydocs	: doxy.config
	doxygen doxy.config
	firefox doxyDocs/html/index.html &

clean :
	rm -rf *.o test bagtest .*sw* doxyDocs


